name: Run Linting
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build docker-compose
        run: docker-compose up -d
      - name: run linting
        run: docker-compose exec -T runtime /bin/bash -c 'rubocop'
